name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -backend-config="bucket=terra-vprofile-state2205" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Get Terraform Outputs
        id: terraform_outputs
        run: |
          echo "::set-output name=public_ip::$(terraform output -yml public_ip)"
          echo "::set-output name=instance_id::$(terraform output -yml instance_id)"

    outputs:
        public_ip: ${{ steps.terraform_outputs.outputs.public_ip }}
        instance_id: ${{ steps.terraform_outputs.outputs.instance_id }}
